# Generated by Django 4.0 on 2022-09-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
